In [161]:
import numpy as np

In [7]:
# 1 dimensional array
a=np.array([1,2,3,4,5,6])
print(a,type (a))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [9]:
# 2 dimensional array
b=np.array([[1,2,3,4],[4,5,6,7]])
print(b,type(b))

[[1 2 3 4]
 [4 5 6 7]] <class 'numpy.ndarray'>


In [11]:
# 3 dimensional array
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c,type(c))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] <class 'numpy.ndarray'>


size = Tell me about No. of element in array

In [14]:
print(a.size)
print(b.size)
print(c.size)

6
8
9


dir() = show what function will be performed by array 

In [16]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

shape = (rows,colume)

In [20]:
print(a.shape)
print(b.shape)
print(c.shape)

(6,)
(2, 4)
(1, 3, 3)


dtype = Type of data present in array

In [26]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
int32


transpose() = which replace rows in colume and colume in rows

In [29]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [33]:
c.transpose()

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [163]:
c.min()

1

In [165]:
c.max()

9

np.empty((rows,cols),dtype)  it is use to get random array of givn dtype

In [51]:
np.empty((4,4),dtype=int)

array([[3801155, 5570652, 6619251, 7536754],
       [4259932, 7143524, 7209065, 4259932],
       [7340144, 6357060, 6357108, 4980828],
       [6488175, 7077985, 5505116, 7143525]])

np.ones((rows,cols),dtype)  it well show "1" in array

In [63]:
x = np.ones(5) #by default dtype is float
print(x)

[1. 1. 1. 1. 1.]


In [65]:
y = np.ones((3,5),dtype=int)
print(y)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


np.zeros((rows,cols),dtype)  it is simmilar to ones

In [79]:
v =np.zeros((rows,cols),dtype)
print(v,type(v))
print(v.size)
print(v.shape)
print(v.ndim)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] <class 'numpy.ndarray'>
20
(4, 5)
2


In [85]:
s=np.zeros((5,4),dtype=str)
print(s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [91]:
np.ones((4,5),dtype=str)

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [87]:
np.zeros((4,5),dtype=bool)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [89]:
np.ones((4,5),dtype=bool)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

np.arange(start,end,step)  it is like range in array

In [98]:
d = np.arange(1,20)
print(d,type(d))
print(d.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
1


In [102]:
d = np.arange(1,20,2)
print(d)

[ 1  3  5  7  9 11 13 15 17 19]


In [106]:
d = np.arange(2,20,2)
print(d)

[ 2  4  6  8 10 12 14 16 18]


reshape((rows,cols)) = it convert rows and colume

In [111]:
d.reshape((3,3))

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Slicing also perform in numpy array

In [117]:
g=np.arange(1,51)
g=g.reshape(10,5)
print(g)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [129]:
g[1][3]=99

In [131]:
g[1]

array([ 6,  7,  8, 99, 10])

In [133]:
g

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8, 99, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

Numpy String operation

In [141]:
s1="sagar is my name. "
s2="I am an indian"

In [143]:
np.char.add(s1,s2)

array('sagar is my name. I am an indian', dtype='<U32')

In [149]:
a = np.char.upper(s1)  #convert into Upper alphabate
print(a)

SAGAR IS MY NAME. 


In [151]:
np.char.lower(a)  #convert into Lower alphabate

array('sagar is my name. ', dtype='<U18')

In [153]:
np.char.split(a)  #convert into list with spliting string

array(list(['SAGAR', 'IS', 'MY', 'NAME.']), dtype=object)

In [157]:
np.char.splitlines(s1)  #convert whole string into list

array(list(['sagar is my name. ']), dtype=object)

In [159]:
np.char.replace(s1,"sagar","Ganesh")

array('Ganesh is my name. ', dtype='<U19')